### ISSUE TITLE
Scheduled for cleanup

### ISSUE THREAD

**Issue by kevinrobinson** [mit-teaching-systems-lab/RailsHelloWorld#2]
Hi @david-rosales!  As part of offboarding, I'm going to clean up this repository since it's not likely to be something we'll use in the lab going forward.  I tried to transfer ownership to you but it seems GitHub doesn't allow that.  If you fork it let me know and I'll remove this, otherwise if I don't hear back from you I'll do that in two weeks.

Thanks!

**Comment by david-rosales** [comment]
@kevinrobinson Ok, I forked it so you can remove it now. Thanks!

**Comment by kevinrobinson** [comment]
@david-rosales thanks, happy summertime! :)
